---
title: '**STOR 320: Intro to Data Science**'
geometry: margin=2
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
    includes:
      in_header: "favicon.html"
  pdf_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}
</style>

This course is an application-driven introduction to data science. Statistical and computational tools are valued throughout the modern workplace from Silicon Valley startups, to marine biology labs, to Wall Street firms. These tools require technical skills such as programming and statistics. They also require professional skills such as communication, teamwork, problem solving, and critical thinking.


- Instructor: **[Mario Giacomazzo](http://www.supermariogiacomazzo.com/)**

- Instructional Assistant: **[Thomas Keefe](http://stat-or.unc.edu/people/graduate-students-department)**

- STOR 320.01 **[Course Syllabus](https://drive.google.com/file/d/18gI5ak5Kdrl6TY2bFfzZA7H2l8uNrXGu/view?usp=sharing)**

- STOR 320.02 **[Course Syllabus](https://drive.google.com/file/d/1h92pSV7o2hzbLCah82hiF9O4ak2IAFRo/view?usp=sharing)**


# **Course Material**

| Date | Lecture | Slides | Tutorial(T) | Lab(L) | Analysis(A)| Project(P)| Solutions  |
|------|---------|--------|---------|:---:|:------------:|:------------:|-----------:|
|Aug. 22|Course Overview, Install R | [Lecture 1](https://drive.google.com/file/d/1_8O_HETMg_MS_jj7zjgfUXKv3QUASBl2/view?usp=sharing) || ||| ||
|Aug. 24|Data Visualization | [Lecture 2](https://drive.google.com/file/d/1OTIdPsv2ap5qsaWLfuw9q5aGY2lMabRw/view?usp=sharing) | [T1](Tutorial/Tutorial 1/Tutorial_1.html) ([.Rmd](https://drive.google.com/file/d/1e0ThTHdZzxsWWg5PI-dG-IURkN1P-bPg/view?usp=sharing)) | [L1](Lab/Lab 1/Lab_1.html) ([.Rmd](https://drive.google.com/file/d/1jXtRTRStUBiAmceTc0rVuxWq0_wsqJ7r/view?usp=sharing))|||[L1](Lab/Lab 1/Solutions_1.html)|
|Aug. 27|Workflow in RMarkdown|[Lecture 3](https://drive.google.com/file/d/1DDl31rRmNHJ17GCIKuLvGpkymxF8uayH/view?usp=sharing)| [T2](Tutorial/Tutorial 2/Tutorial_2.html) ([.zip](https://drive.google.com/file/d/1bLEU0GucAtlX4-VXUydwkesuW3d0pEVB/view?usp=sharing))|||||
|Aug. 29|Data Transformation I|[Lecture 4](https://drive.google.com/file/d/1Zs7-azEFAW1W3sJIHf0kvlfAi49sVFzM/view?usp=sharing)||||||
|Aug. 31|Data Transformation II|[Lecture 5](https://drive.google.com/file/d/1W35ZO5yKH0k-yI3ogr7ilN0r5Fn85Rat/view?usp=sharing)|[T3](Tutorial/Tutorial 3/Tutorial_3.html) ([.Rmd](https://drive.google.com/file/d/1y0UuxOQcwgBS53Cc_COBCOoL832NiXzi/view?usp=sharing))|[L2](Lab/Lab 2/Lab_2.html) ([.Rmd](https://drive.google.com/file/d/1qbrv--zda43E3xj4YlxiqNeLwZjccwOu/view?usp=sharing))|||[L2](Lab/Lab 2/Lab_2_Soln_TK.html)|
|Sep. 3|Don't Labor on Labor Day|||||||
|Sep. 5|Data Transformation III|[Lecture 6](https://drive.google.com/file/d/1kUU2hO2YLJUrrNOv4Uy7tOK8GZcPGqL7/view?usp=sharing)||||||
|Sep. 7|Data Transformation IV|[Lecture 7](https://drive.google.com/file/d/1UGMfheOImYQt63gJ0D_rdLKrlgTQZOjK/view?usp=sharing)|[T4](Tutorial/Tutorial 4/Tutorial_4.html) ([.zip](https://drive.google.com/file/d/1CbVYRmSw7vZua-9ppvsgtcLKuAjhRf-f/view?usp=sharing))||[A1](Analysis/Analysis 1/Analysis_1.html) ([.zip](https://drive.google.com/file/d/1W7enkA4HtOeiS6Q_kwE43T3cgx6wGX9S/view?usp=sharing))||[A1](Analysis/Analysis 1/Solutions_1.html)|
|Sep. 10|Exploratory Data Analysis I|[Lecture 8](https://drive.google.com/file/d/1cwBrbCBpG0nvmcfXrlrpHT5BxREVjr0P/view?usp=sharing)||||||
|Sep. 12|Hurricane Florence|||||||
|Sep. 14|Hurricane Florence|||||||
|Sep. 17|Hurricane Florence|||||||
|Sep. 19|Exploratory Data Analysis II|[Lecture 9](https://drive.google.com/file/d/1HV2oJ5a_dVLBoSCctZr1ir8wzIgoMGVq/view?usp=sharing)|[T5](Tutorial/Tutorial 5/Tutorial_5.html) ([.Rmd](https://drive.google.com/file/d/1NQ5QuKC7ZzaajFkGH39_y-H9gMrAmgjZ/view?usp=sharing))|||||
|Sep. 21|Final Project I|[Lecture 10](https://drive.google.com/file/d/1McGiOljDvGVYgK6CM28d_Ic_mNzQ5SLl/view?usp=sharing)||[L3](Lab/Lab 3/Lab_3.html) ([.Rmd](https://drive.google.com/file/d/14R9FxL7_vBam--s25QYYRM1N4TOs4nTu/view?usp=sharing))||P1, P2|[L3](Lab/Lab 3/Lab_3_Solutions.html)|
|Sep. 24|Data Import|[Lecture 11](https://drive.google.com/file/d/15KvLv179xjfvYSMuoGDKmwicuT0F2UKG/view?usp=sharing)||||||
|Sep. 26|Tidy Data I|[Lecture 12](https://drive.google.com/file/d/1F7eczxlPWwL_YfeuXXpOmbjgHAe7Pnjf/view?usp=sharing)||||||
|Sep. 28|Tidy Data II|[Lecture 13](https://drive.google.com/file/d/1WTsPbnuezz_1ZxI35LwwXPJL7VYlzK8G/view?usp=sharing)|[T6](Tutorial/Tutorial 6/Tutorial_6.html)  ([.Rmd](https://drive.google.com/file/d/1C0p16A8v5NkGio6lKpP6kDxdfjA0X9cq/view?usp=sharing))|[L4](Lab/Lab 4/Lab_4.html) ([.Rmd](https://drive.google.com/file/d/1zLBecpK4G7LSusTdWzYJtoz_FT60tYeb/view?usp=sharing))|||[L4](Lab/Lab 4/Lab_4_Solutions.html)|
|Oct. 1|Joins|[Lecture 14](https://drive.google.com/file/d/1M88xOe34SWkbm7lCQMNX6RQAm_mhCEjk/view?usp=sharing)||||||
|Oct. 3|Web Scraping I|[Lecture 15](https://drive.google.com/file/d/1-JD0sGCSN1oXUf3CA0uT9Yu_l1TPyx6c/view?usp=sharing)|[T7](Tutorial/Tutorial 7/Tutorial_7.html)  ([.Rmd](https://drive.google.com/file/d/1wYT8HjbkzcqZO7AWhxyEM35LfxfP9a2P/view?usp=sharing))|||||
|Oct. 5|Web Scraping II|[Lecture 16](https://drive.google.com/file/d/1Fc-JOvHoaHT8fhUfZmC6uFEaWxipSJrT/view?usp=sharing)|[T8](Tutorial/Tutorial 8/Tutorial_8.html)  ([.zip](https://drive.google.com/file/d/1k86bdmm4tRT2GGyamBlQNXkxfCcSvTl1/view?usp=sharing))||[A2](Analysis/Analysis 2/Analysis_2.html) ([.zip](https://drive.google.com/file/d/1zApD_fi1d2frr3oCLwSutygNmC0oUKe4/view?usp=sharing))||[A2](Analysis/Analysis 2/Solutions_2.html)|
|Oct. 8|Factors|[Lecture 17](https://drive.google.com/file/d/1BuLCYOoCn779L9sr4JwgTbh9QiqBJ38P/view?usp=sharing)||||||
|Oct. 10|Programming I|[Lecture 18](https://drive.google.com/file/d/1SOOh8FZGw7xnhfWCy4g_kMASuB2nFJ6s/view?usp=sharing)|[T9](Tutorial/Tutorial 9/Tutorial_9.html) ([.Rmd](https://drive.google.com/file/d/1mjCIq_f64-G_nNAnqUkZQRHQhDlXS_iM/view?usp=sharing))|||||
|Oct. 12|University Day|||[L5](Lab/Lab 5/Lab_5.html) ([.Rmd](https://drive.google.com/file/d/1nfW4gDWLtADfke1ooVnoTFMmdsut0uk2/view?usp=sharing))|||L5|
|Oct. 15|Programming II|[Lecture 19](https://drive.google.com/file/d/1P_rX98E698AzmxOqKi06Sm0alsX-bfvd/view?usp=sharing)|[T10](Tutorial/Tutorial 10/Tutorial_10.html) ([.Rmd](https://drive.google.com/file/d/1t5LYZnGtC3q-4Mbgx9FDkXw0l-E2nijR/view?usp=sharing))|||||
|Oct. 17|Programming III|[Lecture 20](https://drive.google.com/file/d/1AWk4fcXrVkM4Xm_GxEPrYwONXGpKvCxw/view?usp=sharing)||||||
|Oct. 19|Fall Brizzeak||||||L6|
|Oct. 22|Programming IV|||||||
|Oct. 24||||||||
|Oct. 26||||||||
|Oct. 29||||||||
|Oct. 31||||||||
|Nov. 2||||||||
|Nov. 5||||||||
|Nov. 7||||||||
|Nov. 9||||||||
|Nov. 12||||||||
|Nov. 14||||||||
|Nov. 16||||||||
|Nov. 19||||||||
|Nov. 21|Thanksgiving|||||||
|Nov. 23|Thanksgiving|||||||
|Nov. 26||||||||
|Nov. 28|||||||||
|Nov. 30||||||||
|Dec. 3||||||||
|Dec. 5||||||||
|Dec. 10|STOR 320.01 Final Presentation|||||||
|Dec. 11|STOR 320.02 Final Presentation|||||||
|Dec. 12|Final Written Paper|||||||
|||||||||

<!-- |August 28 | ggplot Wrap-up and Workflow Basics| [Lecture 3](https://www.dropbox.com/s/403yr1vxniw7ave/STOR%20320%20Lecture%203%2008-28-17.pptx?dl=0) | [Reading for 8-28](http://rpubs.com/redrobincl/302494)| -->
<!-- |August 30 | Data Transformations with Dplyr| [Lecture 4](https://www.dropbox.com/s/2so7c7nr4pc9cwb/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Homework for 8-30](http://rpubs.com/redrobincl/302710)| -->
<!-- |Sept. 1 | Data Transformations with Dplyr| [Class Activity](https://www.dropbox.com/s/knonga5b5dzlu0h/STOR%20320%20%E2%80%93%20Class%20Activity%20090117.docx?dl=0) | [Homework for Sept 1](http://rpubs.com/redrobincl/303670)| -->
<!-- |Sept. 6 | Data Transformations with Dplyr| [Still Lecture 4 ](https://www.dropbox.com/s/2so7c7nr4pc9cwb/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Homework for Sept 6](http://rpubs.com/redrobincl/303670)| -->
<!-- |Sept. 8 | Workflow - Scripts, RMarkdown| [Lecture 5 ](https://www.dropbox.com/s/qzprzcyllm481mz/STOR%20320%20Lecture%204%2008-30-17.pptx?dl=0) | [Data Analysis 1](http://rpubs.com/redrobincl/305377)| -->
<!-- |Sept. 11 | Exploratory Data Analysis| [Lecture 6 ](https://www.dropbox.com/s/6vjlvmvi39v79oj/STOR%20320%20Lecture%206%2009-14-17.pptx?dl=0) | | -->
<!-- |Sept. 13 | Exploratory Data Analysis| [Lecture 7 ](https://www.dropbox.com/s/wmvimtcx3y35l8k/STOR%20320%20Lecture%207%2009-13-17.pptx?dl=0) |[Homework](http://rpubs.com/redrobincl/307274) | -->
<!-- |Sept. 15 | Tibbles and R Projects| [Class Activity ](http://rpubs.com/redrobincl/307978) |[Activity as .rmd](https://www.dropbox.com/s/h5huqubm36052bo/September%2015%20Class%20activity.Rmd?dl=0) | -->
<!-- |Sept. 18 | Importing Data| [Lecture 9 ](https://www.dropbox.com/s/gsscenxrw4ken4c/STOR%20320%20Lecture%209%2009-18-17.pptx?dl=0) |[heights.csv](https://www.dropbox.com/s/bjvbfman7i7qhu2/heights.csv?dl=0) | -->
<!-- |Sept. 20 | Tidy Data| [Lecture 10 ](https://www.dropbox.com/s/hqjoiosey01jibs/STOR%20320%20Lecture%2010%2009-20-17.pptx?dl=0) |[MOMA_art.csv](https://drive.google.com/open?id=0B2lwGKhIFjYYb0NMSF92dTVGQ3c)  [MOMA_artists.csv](https://drive.google.com/open?id=0B2lwGKhIFjYYRktDeWtvWHcta3M) | -->
<!-- |Sept. 22 | Tidy Data [Lecture 11 ](https://idc9.github.io/stor390/slides/joins.pdf) |[Joins Homework](https://www.dropbox.com/s/6ew8e0jud3tabsq/joins_lab.Rmd?dl=0) | -->
<!-- |Sept. 25 | Tidy Data - Wrap-up| [Lecture 10 Redux ](https://www.dropbox.com/s/hqjoiosey01jibs/STOR%20320%20Lecture%2010%2009-20-17.pptx?dl=0) |[HW Due Weds.](https://www.dropbox.com/s/6vw4oo6v0cd7zgw/Homework%20Assigned%20Sept%2025%20.Rmd?dl=0) [Script last class](https://www.dropbox.com/s/37dk92fqnkagnq1/Commands_from_Wed_920.R?dl=0)|  -->
<!-- |Sept. 27 | Owning Strings| [Notes ](https://www.dropbox.com/s/43iu67q9iy08x1w/Regex_notes.Rmd?dl=0) |[Slides_______](https://www.dropbox.com/s/2o87qjlm9t2qwew/regex_slides.html?dl=0)     [HW for Friday](http://rpubs.com/redrobincl/312852)|  -->
<!-- |Sept. 29 | Owning Strings| [Slides as Rmd](https://www.dropbox.com/s/b7pdmt2cvlhyo9f/regex_slides.Rmd?dl=0) |[Data Analysis 2](http://rpubs.com/redrobincl/313107)| -->
<!-- |Oct. 2 | Factors| [Slides Lecture 12 ](https://www.dropbox.com/s/3c8naqpeky1yaxk/STOR%20320%20Lecture%2012%2010-02-17.pptx?dl=0) ||  -->
<!-- |Oct. 4 | Programming and Vectors| [Notes L13](http://rpubs.com/redrobincl/314665) |[Slides](http://rpubs.com/redrobincl/315843)| -->
<!-- |Oct. 6 | Programming Lab| [Lab](http://rpubs.com/redrobincl/315815) || -->
<!-- |Oct. 9 | Lists and Loops| [Slides](https://www.dropbox.com/s/d3tvv925un6adla/STOR%20320%20Lecture%2014%2010-09-17.pptx?dl=0) |[HW](https://www.dropbox.com/s/vpebg17uampf706/HW%20for%20Lecture%2014.pptx?dl=0)| -->
<!-- |Oct. 11 | Lists and Loops|[Slides](https://www.dropbox.com/s/d3tvv925un6adla/STOR%20320%20Lecture%2014%2010-09-17.pptx?dl=0) |[Loops HW](http://rpubs.com/redrobincl/316969)| -->
<!-- |Oct. 13 | Intro to Models|[Slides](https://www.dropbox.com/s/svh1yb2cvkgwdz0/STOR%20320%20Lecture%2015%2010-13-17.pptx?dl=0) |[Reading](http://rpubs.com/redrobincl/318157)| -->
<!-- |Oct. 16 | Intro to Models|[Slides](https://www.dropbox.com/s/svh1yb2cvkgwdz0/STOR%20320%20Lecture%2015%2010-13-17.pptx?dl=0) |[HW Due 10-23](http://rpubs.com/redrobincl/319124)| -->
<!-- |Oct. 23 | Intro to Shiny|[Shiny Notes](http://rpubs.com/redrobincl/321857) [Shiny Rmd](https://www.dropbox.com/s/6ndqep5kresuolo/shiny.Rmd?dl=0) |[Apps for Class](https://www.dropbox.com/s/ba3zzm8sny8tuge/beer2burpees.zip?dl=0)| -->
<!-- |Oct. 25 | Data Ethics|[Lecture](https://drive.google.com/open?id=0B2lwGKhIFjYYbVhrcUE5TnJzYTQ)|[data privacy](http://erichorvitz.com/data_privacy_greater_good.pdf)   [_____NYT Uber](https://www.nytimes.com/2017/04/24/technology/personal-data-firm-slice-unroll-me-backlash-uber.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=second-column-region&region=top-news&WT.nav=top-news&_r=0) [Oneill Big Data](https://qz.com/819245/data-scientist-cathy-oneil-on-the-cold-destructiveness-of-big-data/)| -->
<!-- |Oct. 27 | Visualizing Models|[Lecture](https://www.dropbox.com/s/6ut8ki4eynur9ui/STOR%20320%20Lecture%2018%2010-27-17.pptx?dl=0)|[Final Proj Gps](https://www.dropbox.com/s/ukmsxet3gcfkdtl/Final%20Project%20Groups.xls?dl=0) [Final Project](https://www.dropbox.com/s/8i8u8tvla68stpm/description.Rmd?dl=0)|  -->
<!-- |Oct. 30 | Visualizing Models|[Lecture](https://www.dropbox.com/s/6ut8ki4eynur9ui/STOR%20320%20Lecture%2018%2010-27-17.pptx?dl=0)|| -->
<!-- |Nov. 01 | Interaction|[Commands](https://www.dropbox.com/s/ogtcr2e2k4wgfxk/Class%20Commands%20to%20Start%2011-1-17.R?dl=0)|[Homework](http://rpubs.com/redrobincl/325417)| -->
<!-- |Nov. 03 | Interaction (ctd)|[Lecture](https://www.dropbox.com/s/a3uwyj0tsiulq0d/STOR%20320%20Lecture%2018%2011-3-17.pptx?dl=0)|| -->
<!-- |Nov. 06 | Modeling Real Data  |[Activity](https://www.dropbox.com/s/jovc3qvihsbrjnh/STOR%20320%20%E2%80%93%20Diamond%20Activity%20110517.docx?dl=0)|| -->
<!-- |Nov. 10 | Predictive Modeling |[Lecture](https://www.dropbox.com/s/gjnryjbicguu6vt/predictive_modeling.Rmd?dl=0)|[Project Exp An](https://www.dropbox.com/s/q1kzmyvbghvycq2/exploratory_analysis.Rmd?dl=0) [Data Analysis 3](https://www.dropbox.com/s/u50jdu4bsltiy9d/bike_sharing.Rmd?dl=0)| -->
<!-- |Nov. 13 | Get an A on the Project |[Lecture](https://www.dropbox.com/s/0umu2lhlh8gp7u2/communication.key?dl=0)|[Lecture as ppt](https://www.dropbox.com/s/qvupk35xpdj7vo2/communication.pptx?dl=0)| -->
<!-- |Nov. 15 | Classification |[Slides](https://www.dropbox.com/s/vhe5qmad23aawab/slides_classification_md_knn.Rmd?dl=0)|[Everything](https://www.dropbox.com/s/n0qobdswnsrvmse/classification.zip?dl=0)| -->
<!-- |Nov. 20 | Donner Destiny |[Slides](https://www.dropbox.com/s/v5240dew6iif2n7/Donner_Party.Rmd?dl=0)|[Classification Folder   ](https://www.dropbox.com/s/z8ao35ggv2yp2af/classification.zip?dl=0)   [Classification Activity](https://www.dropbox.com/s/d59z1uw6xtzuykr/STOR%20320%20%E2%80%93%20Classification%20Activity%20112017.docx?dl=0)| -->
<!-- |Dec. 4 | Project Presentations and Donners |[Surveys](https://www.dropbox.com/s/eio7oxuyz5n5qsv/Survey%20Links%20for%20Presentations%2012-04-17.docx?dl=0)|[Donner_Modified](https://www.dropbox.com/s/8j7wgalok1f61j5/Donner_Party_update.Rmd?dl=0)  | -->
<!-- |Dec. 4 | Project Presentations and Donners |[Surveys for Exam Day](https://www.dropbox.com/s/heden10bejim063/Survey%20Links%20for%20Presentations%2012-15-17.docx?dl=0)|| -->

# **Assignment Tracker**

All Lab and Analysis assignments are to be submitted via **[Sakai](https://sakai.unc.edu/welcome/)**. 

| Assigned | Lab(L) | Analysis(A) | Due Date (Time) |
|----------|:--------:|:-------------:|----------------:|
| August 24| L1     |              |August 31 (5 PM)|
| August 31| L2     |             |September 7 (5 PM)|
| September 7 | | A1 | September 21 (5 PM)|
| September 14 | L3 ||September 28 (5 PM)|
| September 28 | L4 ||October 5 (5 PM)|
| October 5 | | A2 | October 12 (5PM)|
| October 12 | L5 |  | October 22 (5PM)|
| October 26 | L6 | |October 26 (5PM)|
|          |        |             |           |

# **Final Project Details**

For the final project, each section of STOR 320 will be divided (ideally) into reasearch groups of size 4. To ensure fairness, students will be assigned randomly based on the `sample` function in **R**. May God have mercy on your souls. 

## Research Group Assignments

To find your research group, see below:

- **[STOR 320.01](https://docs.google.com/spreadsheets/d/1XPw0jxwXG5o2v5ywGNrucjpSFP3sqs6uDsIO1s4gDfY/edit?usp=sharing)**

- **[STOR 320.02](https://docs.google.com/spreadsheets/d/1fa9t7pbFAA6MHhT8B-rmMXeRkxCQrSfCR9bZAve0VEE/edit?usp=sharing)**

## Four Roles

Although everyone is responsible for the entire project, each member of the group will be assigned a specific role for accountability and consistency. These four specific roles are described as follows:

- **The Creator:** Schedule and Meet with Dr. Mario or Sir Thomas Keefe to Propose Your Group's Research Idea

- **The Interpreter:** Schedule and Meet with Dr. Mario or Sir Thomas Keefe to Share Findings from Exploratory Analysis

- **The Orator:** Give a Captivating 4 Minute Slideshow Presentation During Final Exam Day

- **The Deliverer:** Deliver Your Group from Evil by Editing and Submitting the Exploratory Analysis and Final Written Paper via SAKAI Before the Deadline

## Four Parts Including Point Values

This final project will be divided into four parts worth a total of 100 points. Each part will have a clear rubric as non-subjective as possible. The parts along with total point values are found below:

* **[P1: Project Proposal](Final Project/Project_Proposal.html)** *(10 Points)*
    + [Data World](https://data.world/)
    + [US Government Data](https://www.data.gov/)
    + [Kaggle](https://www.kaggle.com/)
    + [Free Data Info I](https://www.forbes.com/sites/bernardmarr/2016/02/12/big-data-35-brilliant-and-free-data-sources-for-2016/#63f06f60b54d)
    + [Free Data Info II](https://r-dir.com/reference/datasets.html)

* **[P2: Exploratory Data Analysis](Final Project/Exploratory_Data_Analysis.html)** *(20 Points)*
    + [Template](Final Project/EDA_Template.html) ([.Rmd](https://drive.google.com/file/d/1EM2JXvZ9aHX8oLeB5z1MIWFgDCjAFKvn/view?usp=sharing))
    
* P3: Final Presentation *(30 Points)*

* P4: Final Written Paper *(40 Points)*
    + Template (.Rmd)

## Due Dates of Individual Parts

| Part | Description |Method of Submission| Due Date (Time) |
|------|-------------|-------------------:|----------------:|
| P1  | Project Proposal| Office Hours Meeting     |October 12 (5 PM)|
| P2  | Exploratory Data Analysis |Submit on Sakai|November 9 (5 PM)|
| P3  | Final Presentation (STOR 320.01)|In Gardner 105|December 10 (12 PM)|
| P3  | Final Presentation (STOR 320.02)|In Hanes 120|December 11 (12 PM)|
| P4  | Final Written Paper|Submit on Sakai|December 12 (5 PM)|
||||


# **Reading**

- **[R for Data Science](https://drive.google.com/file/d/1Wca-b3m6CTbBQqO7tUEh_CdD3xVgjYVb/view?usp=sharing)** (R4DS)

- **[R Programming for Data Science](https://drive.google.com/file/d/1XVF5v4MTBhIp_dq9MzTI0TtPfVrF6eaZ/view?usp=sharing)** (RP4DS)

- **[Text Mining with R](https://www.tidytextmining.com/)** (TMwR)

- **[The Art of R Programming](https://drive.google.com/file/d/1gR7Yr9-pIZ-f315bZCXfDj9yPWaZDflD/view?usp=sharing)** (AoRP)

- **[A First Course in Statistical Programming with R](https://drive.google.com/file/d/1NBadpF5MLWI3AFsyWo3nbpQnL8sWeZdT/view?usp=sharing)** (FCSPR)

- **[An Introduction to Statistical Learning](https://drive.google.com/file/d/1jKxVWG89KvWr_-70sOeEeLK4CUB09sRu/view?usp=sharing)** (ISLR)

# **Additional resources**

- **[Rmarkdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)**

- **[ggplot2 Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)**

- **[Color Options](https://paulvanderlaken.files.wordpress.com/2017/08/ggplot2-color-colours-names-cheatsheet.png?w=559&amp;h=1024)**

- **[Data Wrangling Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)**

# **Miscellaneous**

This course was made possible by a grant from the [Data@Carolina](http://data.web.unc.edu/) initiative and a ton of [**input from lots of very smart people**](https://docs.google.com/document/d/1EAIiex92oKphCeBAtmJ9NOyKti76QDsC5lz7vbL7Gwo/edit).

This page was last updated on `r Sys.time()` Eastern Time.
