---
title: "Lecture 8 Workspace"
author: "Mario Giacomazzo"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F)
options(scipen=999)
library(tidyverse)    #Essential Functions
library(knitr)        #kable() for HTML Tables
library(kableExtra)   #HTML Table Styling
library(Ecdat)        #Get Wage1 Dataset
```


```{r}
Wage=as.tibble(Wages1) %>%
  rename(experience=exper) %>%
  arrange(school)
```

```{r}
mean(Wage$sex=="female")
```

```{r}
Wage %>% 
  group_by(sex) %>%
  summarize(n=n())
```

```{r}
ggplot(data=Wage) +
  geom_bar(aes(x=sex,y=..count../sum(..count..)),fill="lightskyblue") + 
  ylab("Relative Frequency") + xlab("") +
  theme_dark()
```


```{r}
Wage %>%
  summarize(n=n(),avg=mean(wage),sd=sd(wage),
            median=median(wage),iqr=IQR(wage))
```


```{r}
ggplot(data=Wage) +
  geom_histogram(aes(x=wage,y=..count../sum(..count..)),
                 fill="lightskyblue",color="black",bins=40) + 
  theme_dark() +  
  ylab("Relative Frequency") + xlab("Wage ($/Hr)")
```

```{r}
ggplot(data=Wage) +
  geom_histogram(aes(x=wage,y=..count../sum(..count..)),bins=40,fill="deepskyblue1",color="black") + 
  theme_dark() +  
  ylab("Relative Frequency")
```
